config/routes.rb
GiftCoordinator::Application.routes.draw do
  devise_for :users

  root :to => "gifts#index"
  resources :gifts

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_filter :find_gift, :only => [:show,
                                     :edit,
                                     :update,
                                     :destroy]
  def index
    @gifts = Gift.all
  end

  def new
    @gift = Gift.new
  end

  def create
    @gift = Gift.new(params[:gift])
    if @gift.save
      flash[:notice] = "Gift has been created."
      redirect_to @gift
    else
      flash[:alert] = "Gift has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @gift.update_attributes(params[:gift])
      flash[:notice] = "Gift has been updated."
      redirect_to @gift
    else
      flash[:alert] = "Gift has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy
    flash[:notice] = "Gift has been deleted."
    redirect_to gifts_path 
  end

  private
    def find_gift
      @gift = Gift.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The gift you were looking for could not be found."
      redirect_to gifts_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
<%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
    <%= f.submit %>
<% end %>

app/views/gifts/edit.html.erb
<h2>Edit Gift</h2>
<%= render "form" %>

app/views/gifts/index.html.erb
<h2>Gifts</h2>
<%= link_to "New Gift", new_gift_path %>
<ul>
  <% @gifts.each do |gift| %>
    <li><%= link_to gift.name, gift %>
  <% end %>
</ul>

app/views/gifts/new.html.erb
<h2>New Gift</h2>
<%= render "form" %>

app/views/gifts/show.html.erb
<h2><%= @gift.name %></h2>
<%= link_to "Edit Gift", edit_gift_path(@gift) %>
<%= link_to "Delete Gift", @gift, :method => :delete, :confirm => "Are you sure you want to delete this gift?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiftCoordinator</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <%= link_to "Sign up", new_user_registration_path %>
</nav>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>